import { useState, useEffect } from 'react'
import axios from 'axios'
import { useAuth } from '@clerk/clerk-react'
import { useNavigate } from 'react-router-dom'
import { Folder, Plus, Loader2, Trash2, Sparkles, Share2, Copy } from 'lucide-react'

export default function Collections() {
  const [collections, setCollections] = useState([])
  const [newCollectionName, setNewCollectionName] = useState('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [isCreating, setIsCreating] = useState(false)
  const [copiedId, setCopiedId] = useState(null)
  const { getToken } = useAuth()
  const navigate = useNavigate()

  const fetchData = async () => {
    try {
      setLoading(true)
      const token = await getToken()
      const colRes = await axios.get('http://localhost:5000/api/collections', { 
        headers: { Authorization: `Bearer ${token}` } 
      })
      setCollections(colRes.data.collections)
      setError(null)
    } catch (err) {
      console.error(err)
      setError("Failed to load collections.")
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchData()
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [getToken])

  const handleCreateCollection = async (e) => {
    e.preventDefault()
    if (!newCollectionName.trim()) return
    setIsCreating(true)
    try {
      const token = await getToken()
      await axios.post('http://localhost:5000/api/collections', { name: newCollectionName }, {
        headers: { Authorization: `Bearer ${token}` }
      })
      setNewCollectionName('')
      await fetchData()
    } catch (err) {
      console.error(err)
      alert("Failed to create collection")
    } finally {
      setIsCreating(false)
    }
  }

  const handleDelete = async (e, id) => {
    e.stopPropagation()
    if (!window.confirm("Are you sure you want to delete this collection?")) return
    try {
      const token = await getToken()
      await axios.delete(`http://localhost:5000/api/collections/${id}`, {
        headers: { Authorization: `Bearer ${token}` }
      })
      await fetchData()
    } catch (err) {
      console.error(err)
      alert("Failed to delete collection.")
    }
  }

  const toggleShare = async (e, id, currentStatus) => {
    e.stopPropagation()
    try {
      const token = await getToken()
      await axios.patch(`http://localhost:5000/api/collections/${id}/share`, { isPublic: !currentStatus }, {
        headers: { Authorization: `Bearer ${token}` }
      })
      await fetchData() // Refresh state
    } catch (err) {
      console.error(err)
      alert("Failed to toggle sharing.")
    }
  }

  const copyShareLink = (e, id) => {
    e.stopPropagation()
    const url = `${window.location.origin}/shared/${id}`
    navigator.clipboard.writeText(url)
    setCopiedId(id)
    setTimeout(() => setCopiedId(null), 2000)
  }

  const manualCollections = collections.filter(c => !c.isAutoGenerated)
  const aiCollections = collections.filter(c => c.isAutoGenerated)

  return (
    <div className="p-6">
      <h1 className="text-2xl font-semibold mb-6">Collections</h1>
      
      {loading && <div className="text-gray-500 animate-pulse">Organizing collections...</div>}
      {error && <div className="text-red-500">{error}</div>}
      
      {/* Manual Collections Section */}
      <div className="mb-12">
        <h2 className="text-xl font-semibold mb-4 text-white/80 border-b border-white/10 pb-2">Your Collections</h2>
        
        <form onSubmit={handleCreateCollection} className="mb-6 flex space-x-3">
          <input 
             type="text" 
             value={newCollectionName}
             onChange={(e) => setNewCollectionName(e.target.value)}
             placeholder="New Collection Name..." 
             className="bg-[#111] border border-white/10 px-4 py-2 rounded-xl text-white outline-none focus:border-blue-500 transition-colors"
          />
          <button 
             type="submit" 
             disabled={isCreating || !newCollectionName.trim()}
             className="bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white px-4 py-2 rounded-xl flex items-center space-x-2 transition-colors"
          >
             {isCreating ? <Loader2 size={16} className="animate-spin" /> : <Plus size={16} />}
             <span>Create</span>
          </button>
        </form>

        {manualCollections.length === 0 ? (
          <p className="text-gray-500 text-sm">No manual collections created yet.</p>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {manualCollections.map((col) => (
              <div 
                key={col._id} 
                className="relative bg-[#111] rounded-2xl border border-white/10 hover:border-blue-500/30 transition-colors group"
              >
                <div 
                  onClick={() => navigate(`/saved?collection=${col._id}&name=${encodeURIComponent(col.name)}`)}
                  className="p-6 flex justify-between items-start cursor-pointer h-full"
                >
                  <div className="flex flex-col h-full w-full">
                    <div className="flex items-center space-x-3 mb-4 truncate">
                      <div className="p-2 bg-blue-500/10 rounded-lg group-hover:bg-blue-500/20 transition-colors shrink-0">
                        <Folder size={24} className="text-blue-400" />
                      </div>
                      <h3 className="text-lg font-medium text-white truncate w-full">{col.name}</h3>
                    </div>
                    
                    <div className="mt-auto pt-4 border-t border-white/5 flex items-center justify-between pointer-events-auto">
                      <div className="flex items-center space-x-2">
                        <button 
                          onClick={(e) => toggleShare(e, col._id, col.isPublic)}
                          className={`flex items-center space-x-1 text-xs px-2 py-1 rounded transition-colors ${col.isPublic ? 'bg-green-500/20 text-green-400 hover:bg-green-500/30' : 'bg-gray-800 text-gray-400 hover:bg-gray-700'}`}
                          title="Toggle Public Sharing"
                        >
                          <Share2 size={12} />
                          <span>{col.isPublic ? 'Public' : 'Private'}</span>
                        </button>
                        
                        {col.isPublic && (
                          <button
                            onClick={(e) => copyShareLink(e, col._id)}
                            className="p-1 rounded bg-white/5 text-gray-300 hover:text-white hover:bg-white/10 transition-colors"
                            title="Copy Link"
                          >
                            {copiedId === col._id ? <span className="text-xs px-1 text-green-400">Copied!</span> : <Copy size={14} />}
                          </button>
                        )}
                      </div>

                      <button 
                        onClick={(e) => handleDelete(e, col._id)} 
                        className="text-gray-500 hover:text-red-400 p-1 rounded hover:bg-red-500/10 transition-all"
                        title="Delete Collection"
                      >
                        <Trash2 size={16} />
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* AI Collections Section */}
      <div className="mb-12">
        <h2 className="text-xl font-semibold mb-4 text-white/80 border-b border-white/10 pb-2 flex items-center gap-2">
          <Sparkles className="text-amber-400" size={20} /> AI Automated Collections
        </h2>
        {aiCollections.length === 0 ? (
          <p className="text-gray-500 text-sm">No AI collections discovered yet. Save some items!</p>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {aiCollections.map((col) => (
              <div 
                key={col._id} 
                className="relative bg-[#111] rounded-2xl border border-white/10 hover:border-amber-500/30 transition-colors group flex flex-col cursor-pointer"
              >
                <div className="p-6 flex-grow" onClick={() => navigate(`/saved?collection=${col._id}&name=${encodeURIComponent(col.name)}`)}>
                  <div className="flex items-center space-x-3 mb-4 truncate w-full">
                    <div className="p-2 bg-amber-500/10 rounded-lg group-hover:bg-amber-500/20 transition-colors shrink-0">
                      <Folder size={24} className="text-amber-400" />
                    </div>
                    <h3 className="text-lg font-medium text-white truncate capitalize w-full">{col.name}</h3>
                  </div>
                </div>
                
                <div className="px-6 pb-4 pt-2 mt-auto border-t border-white/5 flex items-center justify-between">
                  <div className="flex items-center space-x-2">
                    <button 
                      onClick={(e) => toggleShare(e, col._id, col.isPublic)}
                      className={`flex items-center space-x-1 text-xs px-2 py-1 rounded transition-colors ${col.isPublic ? 'bg-green-500/20 text-green-400 hover:bg-green-500/30' : 'bg-gray-800 text-gray-400 hover:bg-gray-700'}`}
                      title="Toggle Public Sharing"
                    >
                       <Share2 size={12} />
                       <span>{col.isPublic ? 'Public' : 'Private'}</span>
                    </button>
                    {col.isPublic && (
                      <button
                        onClick={(e) => copyShareLink(e, col._id)}
                        className="p-1 rounded bg-white/5 text-gray-300 hover:text-white hover:bg-white/10 transition-colors"
                     >
                        {copiedId === col._id ? <span className="text-xs px-1 text-green-400">Copied!</span> : <Copy size={14} />}
                     </button>
                    )}
                  </div>
                  <button 
                    onClick={(e) => handleDelete(e, col._id)} 
                    className="text-gray-500 hover:text-red-400 p-1 rounded hover:bg-red-500/10 transition-all"
                    title="Delete AI Collection"
                  >
                    <Trash2 size={16} />
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

    </div>
  )
}
